### ISSUE TITLE
Add Type and Version to Config File Schema

### ISSUE THREAD

**Issue by chelma** [arkime/arkimeweb#53]
## Description
As part of the AWS-AIO project (https://github.com/arkime/aws-aio), we'd love to have a way to surface Capture and Viewer nodes' `config.ini` file to the user in a way they can easily modify.  Additionally, we need to provide our own special-sauce details to make the solution work.  This creates a need to have an understanding of the config file's "schema".  We have a good start on that with the key/default/text values already provided in-YAML here (https://github.com/arkime/arkimeweb/tree/main/_data/settings).

It is requested that the schema be updated to provide the "type" of each setting value, and which Arkime versions it is for.

**Comment by awick** [comment]
This will live at https://arkime.com/aio-config.json
